# Generated by Django 5.1.7 on 2025-03-15 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='image',
            field=models.ImageField(null=True, upload_to='music_images/'),
        ),
    ]
